import {
  User,
  CreatorProfile,
  Project,
  Campaign,
  CampaignParticipant,
  Submission,
  Reward,
  Notification,
} from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'user-admin',
    email: 'admin@ethioweb3.org',
    name: 'Alazar Kebede',
    role: 'ADMIN',
    category: 'Community Leader',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T09:00:00Z',
    isEmailVerified: true,
  },
  {
    id: 'user-creator-1',
    email: 'dawit@creator.ethioweb3.org',
    name: 'Dawit Alemu',
    role: 'CREATOR',
    category: 'Creator',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-15T11:20:00Z',
    isEmailVerified: true,
  },
  {
    id: 'user-creator-2',
    email: 'selam@creator.ethioweb3.org',
    name: 'Selam Haile',
    role: 'CREATOR',
    category: 'Creator',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-18T14:30:00Z',
    isEmailVerified: true,
  },
  {
    id: 'user-creator-pending',
    email: 'amen@applicant.com',
    name: 'Amen Worku',
    role: 'USER',
    category: 'Creator',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-02-01T10:00:00Z',
    isEmailVerified: true,
  },
  {
    id: 'user-project-sheba',
    email: 'contact@shebafi.org',
    name: 'ShebaFi Team',
    role: 'PROJECT',
    category: 'Project / Company',
    avatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-12T08:00:00Z',
    isEmailVerified: true,
  },
];

export const SEED_CREATORS: CreatorProfile[] = [
  {
    id: 'creator-dawit',
    userId: 'user-creator-1',
    displayName: 'Dawit Alemu',
    username: 'dawit_web3',
    bio: 'Web3 educator and Amharic crypto content creator. Passionate about bringing DeFi knowledge to East Africa.',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    languages: ['Amharic', 'English'],
    platforms: {
      x: 'https://x.com/dawit_web3',
      telegram: 'https://t.me/ethio_crypto_insights',
      youtube: 'https://youtube.com/@DawitWeb3',
    },
    audience: {
      followerCount: 14500,
      avgViews: 4800,
      engagementRate: 6.8,
      topLocations: ['Ethiopia', 'Kenya', 'United States'],
    },
    categories: ['Web3 education', 'DeFi', 'Crypto'],
    experience: {
      yearsInWeb3: 3,
      previousCampaigns: 'Arbitrum Africa Launch, Polygon Guild Addis workshop',
      portfolioLinks: ['https://x.com/dawit_web3/status/1789012345'],
      sampleContentUrl: 'https://x.com/dawit_web3/status/1789012345',
    },
    status: 'APPROVED',
    appliedAt: '2026-01-15T11:30:00Z',
    reviewedAt: '2026-01-16T10:00:00Z',
  },
  {
    id: 'creator-selam',
    userId: 'user-creator-2',
    displayName: 'Selam Haile',
    username: 'selam_crypto',
    bio: 'DeFi researcher and tech writer decoding L2 rollups and stablecoins for African cross-border trade.',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    languages: ['Amharic', 'English', 'Oromo'],
    platforms: {
      x: 'https://x.com/selam_crypto',
      telegram: 'https://t.me/selam_defi',
    },
    audience: {
      followerCount: 22800,
      avgViews: 8200,
      engagementRate: 7.4,
      topLocations: ['Ethiopia', 'UAE', 'United Kingdom'],
    },
    categories: ['DeFi', 'Finance', 'Technology'],
    experience: {
      yearsInWeb3: 4,
      previousCampaigns: 'ShebaFi Alpha sprint, MakerDAO Africa summit',
      portfolioLinks: ['https://x.com/selam_crypto/status/1789098765'],
    },
    status: 'APPROVED',
    appliedAt: '2026-01-18T14:40:00Z',
    reviewedAt: '2026-01-19T09:00:00Z',
  },
  {
    id: 'creator-amen-pending',
    userId: 'user-creator-pending',
    displayName: 'Amen Worku',
    username: 'amen_web3',
    bio: 'Community builder and developer advocate based in Hawassa. Organizing campus blockchain meetups.',
    country: 'Ethiopia',
    city: 'Hawassa',
    languages: ['Amharic', 'English', 'Sidamo'],
    platforms: {
      x: 'https://x.com/amen_web3',
      telegram: 'https://t.me/hawassa_blockchain',
    },
    audience: {
      followerCount: 4200,
      avgViews: 1900,
      engagementRate: 5.2,
      topLocations: ['Ethiopia'],
    },
    categories: ['Blockchain development', 'Web3 education'],
    experience: {
      yearsInWeb3: 2,
      previousCampaigns: 'Hawassa University Techfest Web3 Track',
      portfolioLinks: ['https://github.com/amen-worku'],
    },
    status: 'PENDING',
    appliedAt: '2026-02-01T10:15:00Z',
  },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: 'project-sheba',
    userId: 'user-project-sheba',
    name: 'ShebaFi',
    logoUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=150&auto=format&fit=crop&q=80',
    website: 'https://shebafi.network',
    description: 'Decentralized Ethiopian Birr-backed stablecoin and non-custodial cross-border remittance gateway.',
    category: 'DeFi & Payments',
    ecosystem: 'Ethereum / Arbitrum',
    contactEmail: 'contact@shebafi.org',
    socialLinks: {
      x: 'https://x.com/shebafi',
      telegram: 'https://t.me/shebafi_announcements',
    },
    representativeName: 'Kalkidan Teshale',
    status: 'APPROVED',
    appliedAt: '2026-01-12T08:30:00Z',
    reviewedAt: '2026-01-13T12:00:00Z',
  },
  {
    id: 'project-arbitrum',
    userId: 'user-project-arbitrum',
    name: 'Arbitrum Africa Initiative',
    logoUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=150&auto=format&fit=crop&q=80',
    website: 'https://arbitrum.io',
    description: 'Empowering East African developers and creators to build low-cost Ethereum Layer 2 applications.',
    category: 'Layer 2 / Scaling',
    ecosystem: 'Arbitrum Nitro',
    contactEmail: 'africa@arbitrum.foundation',
    socialLinks: {
      x: 'https://x.com/arbitrum_africa',
    },
    representativeName: 'Samuel Mensah',
    status: 'APPROVED',
    appliedAt: '2026-01-10T10:00:00Z',
    reviewedAt: '2026-01-11T14:00:00Z',
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: 'campaign-arbitrum-builders',
    title: 'Arbitrum Africa Builders & Creators Campaign',
    slug: 'arbitrum-africa-builders',
    shortDescription: 'Educate Ethiopian developers and users about low gas fees, Ethereum L2 rollups, and local Web3 apps.',
    description: `We are looking for creative Ethiopian content creators, technical writers, and community voices to showcase the power of Arbitrum Layer 2.

Your mission:
- Create informative X threads or explainer posts highlighting why sub-cent transaction fees matter for African digital commerce.
- Share tutorials or screenshots using Arbitrum bridges and dApps.
- Engage with followers and answer newcomer questions in Amharic and English.`,
    coverImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop&q=80',
    projectId: 'project-arbitrum',
    projectName: 'Arbitrum Africa Initiative',
    projectLogo: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    startDate: '2026-02-01T00:00:00Z',
    endDate: '2026-03-31T23:59:59Z',
    rewardPool: {
      total: 3500,
      currency: 'USDC',
      rewardStructure: 'Top 10 creators split 70% based on verified engagement score; 30% distributed to all qualified submissions.',
    },
    maxParticipants: 50,
    targetPlatforms: ['X'],
    contentRequirements: [
      'Original post or thread on X explaining Arbitrum L2 benefits for Ethiopian users.',
      'Must tag @Arbitrum_Africa and use required hashtags.',
      'At least one visual asset (infographic, short video, or clear dApp screenshot).',
      'Minimum 200 characters of meaningful educational context.',
    ],
    requiredHashtags: ['#ArbitrumAfrica', '#EthioWeb3', '#Layer2'],
    requiredMentions: ['@Arbitrum_Africa', '@EthioWeb3'],
    campaignRules: [
      'Zero tolerance for engagement farming bots or fake views.',
      'Only posts published after campaign start date are eligible.',
      'Content must be respectful, accurate, and original.',
      'Post URL must be submitted to the dashboard within 48 hours of posting.',
    ],
    createdAt: '2026-01-28T14:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'campaign-shebafi-sprint',
    title: 'ShebaFi Birr-to-Stablecoin Awareness Sprint',
    slug: 'shebafi-stablecoin-sprint',
    shortDescription: 'Demystify local currency on-ramps and decentralized remittances for Ethiopian freelancers and diaspora.',
    description: `ShebaFi provides seamless on-ramp rails from local payment methods into stablecoins. Help your community understand how decentralized finance solves cross-border transaction delays and protects purchasing power.

Key themes to cover:
1. Inflation hedging with dollar-backed stable assets.
2. Direct freelance payouts for remote developers.
3. How to set up a self-custody wallet safely.`,
    coverImage: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=800&auto=format&fit=crop&q=80',
    projectId: 'project-sheba',
    projectName: 'ShebaFi',
    projectLogo: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    startDate: '2026-02-10T00:00:00Z',
    endDate: '2026-03-25T23:59:59Z',
    rewardPool: {
      total: 2000,
      currency: 'USDT',
      rewardStructure: 'Rank 1: 500 USDT, Rank 2: 350 USDT, Rank 3: 250 USDT, Ranks 4-10: 100 USDT each.',
    },
    maxParticipants: 40,
    targetPlatforms: ['X'],
    contentRequirements: [
      'Educational breakdown in Amharic or English.',
      'Include official link to shebafi.network.',
      'Tag @ShebaFi and use #ShebaFi #EthioCrypto.',
    ],
    requiredHashtags: ['#ShebaFi', '#EthioCrypto', '#AddisWeb3'],
    requiredMentions: ['@ShebaFi'],
    campaignRules: [
      'No investment advice or speculative claims. Focus strictly on technology and utility.',
      'Must submit valid X post URL.',
    ],
    createdAt: '2026-02-05T12:00:00Z',
    updatedAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'campaign-polygon-odyssey',
    title: 'Polygon Addis Developer Odyssey 2026',
    slug: 'polygon-addis-dev-odyssey',
    shortDescription: 'Calling developer advocates and builders to create smart contract tutorials and dApp showcases on Polygon zkEVM.',
    description: `Connect with the 5,000+ member developer ecosystem in Ethiopia. Share coding walkthroughs, open-source templates, and zero-knowledge rollup use-cases.`,
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    projectId: 'project-arbitrum',
    projectName: 'Polygon Addis Guild',
    projectLogo: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=150&auto=format&fit=crop&q=80',
    status: 'APPROVED',
    startDate: '2026-03-15T00:00:00Z',
    endDate: '2026-04-30T23:59:59Z',
    rewardPool: {
      total: 1800,
      currency: 'USDC',
      rewardStructure: 'Prizes for top 5 technical guides and community threads.',
    },
    maxParticipants: 30,
    targetPlatforms: ['X'],
    contentRequirements: [
      'Technical post with GitHub repo link or code snippet.',
      'Focus on EVM compatibility and ZK tech.',
    ],
    requiredHashtags: ['#PolygonAddis', '#EthioDevs', '#zkEVM'],
    requiredMentions: ['@PolygonAddis'],
    campaignRules: [
      'Original code or educational content required.',
    ],
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-25T11:00:00Z',
  },
];

export const SEED_PARTICIPANTS: CampaignParticipant[] = [
  {
    id: 'part-dawit-arbitrum',
    campaignId: 'campaign-arbitrum-builders',
    creatorId: 'creator-dawit',
    creatorName: 'Dawit Alemu',
    creatorUsername: 'dawit_web3',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    joinedAt: '2026-02-02T08:00:00Z',
    status: 'ACTIVE',
    totalPosts: 2,
    totalImpressions: 11400,
    totalEngagements: 890,
    score: 1840,
    rank: 1,
  },
  {
    id: 'part-selam-arbitrum',
    campaignId: 'campaign-arbitrum-builders',
    creatorId: 'creator-selam',
    creatorName: 'Selam Haile',
    creatorUsername: 'selam_crypto',
    creatorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    joinedAt: '2026-02-03T11:30:00Z',
    status: 'ACTIVE',
    totalPosts: 1,
    totalImpressions: 8900,
    totalEngagements: 670,
    score: 1420,
    rank: 2,
  },
  {
    id: 'part-dawit-sheba',
    campaignId: 'campaign-shebafi-sprint',
    creatorId: 'creator-dawit',
    creatorName: 'Dawit Alemu',
    creatorUsername: 'dawit_web3',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    joinedAt: '2026-02-11T09:00:00Z',
    status: 'ACTIVE',
    totalPosts: 1,
    totalImpressions: 4600,
    totalEngagements: 380,
    score: 790,
    rank: 1,
  },
];

export const SEED_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-1',
    campaignId: 'campaign-arbitrum-builders',
    campaignTitle: 'Arbitrum Africa Builders & Creators Campaign',
    creatorId: 'creator-dawit',
    creatorUsername: 'dawit_web3',
    creatorDisplayName: 'Dawit Alemu',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    platform: 'X',
    externalPostId: '1892300100234567890',
    url: 'https://x.com/dawit_web3/status/1892300100234567890',
    contentText: 'Why Ethereum Layer 2 rollups like @Arbitrum_Africa are a game-changer for Ethiopian builders: 1/10 🧵 Gas fees drop from $5 to < $0.01. Here is how local fintechs can leverage Nitro #ArbitrumAfrica #EthioWeb3',
    submittedAt: '2026-02-04T10:30:00Z',
    lastSyncedAt: '2026-03-01T15:00:00Z',
    status: 'VERIFIED',
    metrics: {
      impressions: 6800,
      likes: 245,
      replies: 42,
      reposts: 78,
      bookmarks: 35,
      engagementRate: 5.88,
    },
    snapshots: [
      {
        id: 'snap-1-1',
        submissionId: 'sub-1',
        timestamp: '2026-02-04T12:00:00Z',
        impressions: 1200,
        likes: 45,
        replies: 8,
        reposts: 12,
        bookmarks: 5,
      },
      {
        id: 'snap-1-2',
        submissionId: 'sub-1',
        timestamp: '2026-02-05T18:00:00Z',
        impressions: 4300,
        likes: 160,
        replies: 28,
        reposts: 48,
        bookmarks: 22,
      },
      {
        id: 'snap-1-3',
        submissionId: 'sub-1',
        timestamp: '2026-03-01T15:00:00Z',
        impressions: 6800,
        likes: 245,
        replies: 42,
        reposts: 78,
        bookmarks: 35,
      },
    ],
    score: 1118,
  },
  {
    id: 'sub-2',
    campaignId: 'campaign-arbitrum-builders',
    campaignTitle: 'Arbitrum Africa Builders & Creators Campaign',
    creatorId: 'creator-selam',
    creatorUsername: 'selam_crypto',
    creatorDisplayName: 'Selam Haile',
    creatorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    platform: 'X',
    externalPostId: '1892400500123456789',
    url: 'https://x.com/selam_crypto/status/1892400500123456789',
    contentText: 'A deep dive into cross-border settlements between Addis Ababa and Nairobi using stablecoins on Arbitrum. Speed: 2 seconds. Cost: 0.003 USD. @Arbitrum_Africa #EthioWeb3 #Layer2',
    submittedAt: '2026-02-06T14:15:00Z',
    lastSyncedAt: '2026-03-01T15:00:00Z',
    status: 'VERIFIED',
    metrics: {
      impressions: 8900,
      likes: 310,
      replies: 54,
      reposts: 95,
      bookmarks: 48,
      engagementRate: 5.69,
    },
    snapshots: [
      {
        id: 'snap-2-1',
        submissionId: 'sub-2',
        timestamp: '2026-02-06T16:00:00Z',
        impressions: 2100,
        likes: 85,
        replies: 12,
        reposts: 26,
        bookmarks: 14,
      },
      {
        id: 'snap-2-2',
        submissionId: 'sub-2',
        timestamp: '2026-03-01T15:00:00Z',
        impressions: 8900,
        likes: 310,
        replies: 54,
        reposts: 95,
        bookmarks: 48,
      },
    ],
    score: 1420,
  },
  {
    id: 'sub-3',
    campaignId: 'campaign-arbitrum-builders',
    campaignTitle: 'Arbitrum Africa Builders & Creators Campaign',
    creatorId: 'creator-dawit',
    creatorUsername: 'dawit_web3',
    creatorDisplayName: 'Dawit Alemu',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    platform: 'X',
    externalPostId: '1893100200987654321',
    url: 'https://x.com/dawit_web3/status/1893100200987654321',
    contentText: 'Ethiopian devs! Testing smart contracts on Arbitrum Sepolia testnet takes 5 minutes. Check out our quick step-by-step guide in Amharic 🇪🇹👇 #EthioWeb3 #ArbitrumAfrica',
    submittedAt: '2026-02-14T09:40:00Z',
    lastSyncedAt: '2026-03-01T15:00:00Z',
    status: 'VERIFIED',
    metrics: {
      impressions: 4600,
      likes: 180,
      replies: 28,
      reposts: 46,
      bookmarks: 29,
      engagementRate: 6.15,
    },
    snapshots: [
      {
        id: 'snap-3-1',
        submissionId: 'sub-3',
        timestamp: '2026-02-14T11:00:00Z',
        impressions: 1100,
        likes: 52,
        replies: 7,
        reposts: 14,
        bookmarks: 8,
      },
      {
        id: 'snap-3-2',
        submissionId: 'sub-3',
        timestamp: '2026-03-01T15:00:00Z',
        impressions: 4600,
        likes: 180,
        replies: 28,
        reposts: 46,
        bookmarks: 29,
      },
    ],
    score: 722,
  },
];

export const SEED_REWARDS: Reward[] = [
  {
    id: 'rew-1',
    campaignId: 'campaign-arbitrum-builders',
    campaignTitle: 'Arbitrum Africa Builders & Creators Campaign',
    creatorId: 'creator-dawit',
    creatorName: 'Dawit Alemu',
    creatorUsername: 'dawit_web3',
    amount: 650,
    currency: 'USDC',
    rank: 1,
    status: 'APPROVED',
    createdAt: '2026-02-28T12:00:00Z',
  },
  {
    id: 'rew-2',
    campaignId: 'campaign-arbitrum-builders',
    campaignTitle: 'Arbitrum Africa Builders & Creators Campaign',
    creatorId: 'creator-selam',
    creatorName: 'Selam Haile',
    creatorUsername: 'selam_crypto',
    amount: 450,
    currency: 'USDC',
    rank: 2,
    status: 'APPROVED',
    createdAt: '2026-02-28T12:00:00Z',
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-creator-1',
    title: 'X Submission Verified! 🚀',
    message: 'Your post for "Arbitrum Africa Builders" was verified and reached 6,800+ impressions.',
    type: 'success',
    read: false,
    createdAt: '2026-02-04T12:30:00Z',
    link: 'my-posts',
  },
  {
    id: 'notif-2',
    userId: 'user-creator-1',
    title: 'Reward Allocation Approved',
    message: 'You have been awarded 650 USDC for rank #1 in the Arbitrum campaign leaderboard.',
    type: 'reward',
    read: false,
    createdAt: '2026-02-28T12:05:00Z',
    link: 'rewards',
  },
  {
    id: 'notif-3',
    userId: 'user-admin',
    title: 'New Creator Application Pending',
    message: 'Amen Worku (@amen_web3) from Hawassa submitted a creator verification request.',
    type: 'warning',
    read: false,
    createdAt: '2026-02-01T10:15:00Z',
    link: 'admin-creators',
  },
];
